name: CI
on:
  push:
    branches: ['**']
  pull_request:
    branches: ['**']
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
permissions:
  contents: read
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - name: Install dependencies
        run: bun install --frozen-lockfile || bun install
      - name: Lint
        run: bun run lint
      - name: Typecheck
        run: bun run typecheck
      - name: Build
        run: bun run build
      - name: Tests
        run: bun run test
